#!/usr/bin/env bash

[[ "$OSTYPE" =~ ^linux ]] || {
    echo "Cannot run this here: OSTYPE=$OSTYPE"
    exit 1
}
[[ -z "$CONTAINER_ID" ]] || {
    echo "Already inside of the container '$CONTAINER_ID'."
    exit 1
}
type distrobox >/dev/null 2>&1 || {
    echo "distrobox is not installed"
    exit 1
}

extra_create_args=()

set -x
if [[ -d /etc/nixos ]]; then
    case "$1" in
    fbox)
        distrobox create \
            --image ghcr.io/aorith/fbox:latest \
            "${extra_create_args[@]}" \
            --home ~/homes/fbox \
            --name fbox &&
            distrobox enter --clean-path fbox
        ;;
    fbox-slim)
        distrobox create \
            --image ghcr.io/aorith/fbox-slim:latest \
            "${extra_create_args[@]}" \
            --home ~/homes/fbox-slim \
            --name fbox-slim &&
            distrobox enter --clean-path fbox-slim
        ;;
    archbox)
        distrobox create \
            --image ghcr.io/aorith/archbox:latest \
            "${extra_create_args[@]}" \
            --home ~/homes/archbox \
            --name archbox &&
            distrobox enter --clean-path archbox
        ;;
    ubox)
        distrobox create \
            --image docker.io/ubuntu:latest \
            "${extra_create_args[@]}" \
            --home ~/homes/ubox \
            --name ubox &&
            distrobox enter --clean-path ubox
        ;;
    tbox)
        distrobox create \
            --image registry.opensuse.org/opensuse/distrobox:latest \
            "${extra_create_args[@]}" \
            --home ~/homes/tbox \
            --name tbox &&
            distrobox enter --clean-path tbox
        ;;
    *)
        echo "Unknown distrobox: '$1'"
        exit 1
        ;;
    esac
else
    case "$1" in
    fbox)
        distrobox create \
            --image ghcr.io/aorith/fbox:latest \
            "${extra_create_args[@]}" \
            --name fbox &&
            distrobox enter fbox
        ;;
    fbox-slim)
        distrobox create \
            --image ghcr.io/aorith/fbox-slim:latest \
            "${extra_create_args[@]}" \
            --name fbox-slim &&
            distrobox enter fbox-slim
        ;;
    archbox)
        distrobox create \
            --image ghcr.io/aorith/archbox:latest \
            "${extra_create_args[@]}" \
            --home ~/homes/archbox \
            --name archbox &&
            distrobox enter archbox
        ;;
    ubox)
        distrobox create \
            --image docker.io/ubuntu:latest \
            "${extra_create_args[@]}" \
            --home ~/homes/ubox \
            --name ubox &&
            distrobox enter ubox
        ;;
    tbox)
        distrobox create \
            --image registry.opensuse.org/opensuse/distrobox:latest \
            "${extra_create_args[@]}" \
            --home ~/homes/tbox \
            --name tbox &&
            distrobox enter tbox
        ;;
    *)
        echo "Unknown distrobox: '$1'"
        exit 1
        ;;
    esac
fi
