# vim: ft=bash
[ -z "$PS1" ] && return

# Bash version check
if ((BASH_VERSINFO[0] < 5))
then
    echo "Bash is not up-to-date - minimum version required is 5"
    echo "Current version is: ${BASH_VERSINFO[0]}"
fi

# bash completion
for completion in /etc/bash_completion \
    /usr/share/bash-completion/bash_completion \
    /usr/local/etc/profile.d/bash_completion.sh \
    /usr/local/share/bash-completion/bash_completion
do
    [[ -r "$completion" ]] && . "$completion"
done
unset completion

shopt -s nullglob

# source local alias/functions ...
[ -r "${HOME}"/.bash_local ] && . "${HOME}"/.bash_local

# SOURCE ENV FILES IN ORDER
env_files="$(for env_file in "${DOTFILES}"/topics/*/env/* "${PRIVATE_DOTFILES}"/topics/*/env/*; do
    echo "$env_file"
done | awk -F'/' '{print $NF,$0}' | sort -n | awk '{print $2}')"
for env_file in $env_files; do
    . "$env_file"
done
unset env_file env_files

shopt -u nullglob

source "${DOTFILES}/topics/bash/etc/colors.bash"
source "${DOTFILES}/topics/bash/etc/prompt.bash"

trap '__before_command' DEBUG
PROMPT_COMMAND='__prompt_command'
