# vim: ft=bash
[ -z "$PS1" ] && return

# bash completion
for completion in /etc/bash_completion \
    /usr/share/bash-completion/bash_completion \
    /usr/local/etc/profile.d/bash_completion.sh \
    /usr/local/share/bash-completion/bash_completion
do
    [[ -r "$completion" ]] && . "$completion"
done
unset completion

shopt -s nullglob

# Nix
test -e "${HOME}/.nix-profile/etc/profile.d/nix.sh" && \
    . "${HOME}/.nix-profile/etc/profile.d/nix.sh"

# source local alias/functions ...
[ -r "${HOME}"/.bash_local ] && . "${HOME}"/.bash_local

# SOURCE ENV FILES IN ORDER
for env_file in "${ENV_FILES_FOLDER}"/*; do
    . "$env_file"
done
unset env_file

source "${DOTFILES}/topics/bash/etc/colors.bash"
source "${DOTFILES}/topics/bash/etc/prompt.bash"

# disable it: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=666933
shopt -u nullglob

# Bash version check
if ((BASH_VERSINFO[0] < 5))
then
    echo "Bash is not up-to-date - minimum version required is 5"
    echo "Current version is: ${BASH_VERSINFO[0]}"
else
    trap '__before_command' DEBUG
fi

PROMPT_COMMAND='__prompt_command'
