# ~/.bashrc
# shellcheck disable=SC1090,SC2155,SC1091

[[ $- == *i* ]] || return

. ~/githome/dotfiles/topics/shell/etc/common/env.sh
. ~/githome/dotfiles/topics/shell/etc/common/aliases.sh

. ~/githome/dotfiles/topics/shell/src/bash/functions.sh
. ~/githome/dotfiles/topics/shell/src/bash/completion.sh

shopt -s checkjobs checkwinsize histappend cmdhist lithist globstar 2>/dev/null
set -o notify # notify completed background jobs immediately

export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/.bash_history"
export HISTCONTROL="erasedups:ignoredups"
export HISTSIZE=16000
#export HISTTIMEFORMAT='%d/%h %H:%M:%S $ '
export HISTIGNORE="exit:ls:bg:fg:history:clear:cd"

# Containers
if [[ -z "$CONTAINER_ID" ]] && [[ -e /run/.containerenv ]]; then
    export CONTAINER_ID=$(awk -F '=' '/^name=/ {print $2}' /run/.containerenv | tr -d '"')
fi

# Fzf
if command -v fzf >/dev/null 2>&1; then
    eval "$(fzf --bash)"
fi

# Television
# if command -v tv >/dev/null 2>&1; then
#     eval "$(tv init bash)"
# fi

# Optionally use starship
# if command -v starship >/dev/null 2>&1; then
#     set_win_title() {
#         echo -ne "\033]0;$USER@$HOSTNAME $PWD\007"
#     }
#     # shellcheck disable=SC2034
#     starship_precmd_user_func="set_win_title"
#     eval "$(starship init bash)"
# else
#     . "${DOTFILES}"/topics/shell/src/bash/etc/prompt.sh
# fi
. "${DOTFILES}"/topics/shell/src/bash/etc/prompt.sh
