# vim: ft=bash
my_blk='\[\e[30m\]'     # Black - Foreground
my_red='\[\e[31m\]'     # Red
my_grn='\[\e[32m\]'     # Green
my_ylw='\[\e[33m\]'     # Yellow
my_blu='\[\e[34m\]'     # Blue
my_pur='\[\e[35m\]'     # Purple
my_cyn='\[\e[36m\]'     # Cyan
my_wht='\[\e[37m\]'     # White
my_bakblk='\[\e[40m\]'  # Black - Background
my_bakred='\[\e[41m\]'  # Red
my_bakgrn='\[\e[42m\]'  # Green
my_bakylw='\[\e[43m\]'  # Yellow
my_bakblu='\[\e[44m\]'  # Blue
my_bakpur='\[\e[45m\]'  # Purple
my_bakcyn='\[\e[46m\]'  # Cyan
my_bakwht='\[\e[47m\]'  # White
my_bld='\[\e[1m\]'      # Bold
my_dim='\[\e[2m\]'      # Dim
my_ita='\[\e[3m\]'      # Italic
my_und='\[\e[4m\]'      # Underline
my_blink='\[\e[5m\]'    # Blinking
my_rvrs='\[\e[7m\]'     # Reverse
my_invis='\[\e[8m\]'    # Invisible
my_rst='\[\e[0m\]'      # Text Reset

