[general]
import = ["~/.config/alacritty/env.toml", "~/.config/alacritty/theme.toml"]

[window]
dynamic_padding = true
dynamic_title = false

[window.padding]
x = 4
y = 4

[bell]
animation = "EaseOutExpo"
color = "#777777"
duration = 10

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Never"
shape = "Block"

[mouse]
hide_when_typing = false

[scrolling]
history = 1000

[selection]
save_to_clipboard = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(https://|http://|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
