[general]
import = ["~/.config/alacritty/env.toml", "~/.config/alacritty/theme.toml"]

[font]
size = 16
#offset = { y = 2 }

# Nerd Font Mono == Fully monospaced, smaller icons
# Nerd Font == Partially monospaced, bigger icons (2wide icons, terminal has to support them)
normal = { family = "Hack Nerd Font" }

[window]
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"

[window.padding]
x = 4
y = 4

[bell]
animation = "EaseOutExpo"
color = "#777777"
duration = 10

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
# Without this, cursor is hard to see on neovim when searching or using 'f'
text = "#000000"
cursor = "#35f080"

[cursor]
style = { shape = "Block", blinking = "Never" }
thickness = 0.20

[mouse]
hide_when_typing = false

[scrolling]
history = 1000

[selection]
save_to_clipboard = true

[hints]
enabled = []

# [[hints.enabled]]
# command = "open"
# hyperlinks = true
# mouse.enabled = true
# post_processing = true
# regex = "(https:|http:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

# Disable 'ToggleViMode'
[[keyboard.bindings]]
key = "Space"
mods = "Shift|Control"
action = "ReceiveChar"

# Disable 'Search'
[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "ReceiveChar"
[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "ReceiveChar"
[[keyboard.bindings]]
key = "F"
mods = "Command"
action = "ReceiveChar"
[[keyboard.bindings]]
key = "B"
mods = "Command"
action = "ReceiveChar"
