[general]
import = ["~/.config/alacritty/env.toml", "~/.config/alacritty/theme.toml"]

[font]
size = 15
offset = { y = 6 }
glyph_offset = { y = 3 }

# Nerd Font Mono == Fully monospaced, smaller icons
# Nerd Font == Partially monospaced, bigger icons (2wide icons, terminal has to support them)
#normal = { family = "JetBrainsMono Nerd Font" }
normal = { family = "Hack Nerd Font" }

[window]
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"

[window.padding]
x = 4
y = 4

[bell]
animation = "EaseOutExpo"
color = "#777777"
duration = 10

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
# Without this, cursor is hard to see on neovim when searching or using 'f'
text = "#000000"
cursor = "#35f080"

[cursor.style]
blinking = "Never"
shape = "Block"

[mouse]
hide_when_typing = false

[scrolling]
history = 1000

[selection]
save_to_clipboard = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
mouse.enabled = true
regex = "(https:|http:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
