[window]
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[window.padding]
x = 4
y = 4

[font]
size = 16
offset = { x = 0, y = 4 }

normal = { family = "Hack Nerd Font Mono" }

[keyboard]

bindings = [
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "N", mods = "Command|Shift", action = "SpawnNewInstance" },
  { key = "F12", action = "ToggleSimpleFullscreen" },

  { key = "Space", mods = "Alt", chars = "\u0020" },
  { key = "Space", mods = "Command", chars = "\u0020" },

  { key = "W", mods = "Command", chars = "\u0002x" },
  { key = "T", mods = "Command", chars = "\u0002c" },
  { key = "T", mods = "Command|Shift", chars = "\u0002C" },

  { key = "H", mods = "Command", chars = "\u0002h" },
  { key = "J", mods = "Command", chars = "\u0002j" },
  { key = "K", mods = "Command", chars = "\u0002k" },
  { key = "L", mods = "Command", chars = "\u0002l" },

  { key = "H", mods = "Command|Shift", chars = "\u0002H" },
  { key = "J", mods = "Command|Shift", chars = "\u0002J" },
  { key = "K", mods = "Command|Shift", chars = "\u0002K" },
  { key = "L", mods = "Command|Shift", chars = "\u0002L" },

  { key = "Left", mods = "Command", chars = "\u0002\u0008" },
  { key = "Down", mods = "Command", chars = "\u0002\u000a" },
  { key = "Up", mods = "Command", chars = "\u0002\u000b" },
  { key = "Right", mods = "Command", chars = "\u0002\u000c" },

  { key = "Enter", mods = "Command|Shift", chars = "\u0002\u0020" },
  { key = "D", mods = "Command", chars = "\u0002\u0025" },
  { key = "D", mods = "Command|Shift", chars = "\u0002\u0022" },
  { key = "S", mods = "Command", chars = "\u0002s" },

  { key = "1", mods = "Command", chars = "\u00021" },
  { key = "2", mods = "Command", chars = "\u00022" },
  { key = "3", mods = "Command", chars = "\u00023" },
  { key = "4", mods = "Command", chars = "\u00024" },
  { key = "5", mods = "Command", chars = "\u00025" },
  { key = "6", mods = "Command", chars = "\u00026" },
  { key = "7", mods = "Command", chars = "\u00027" },
  { key = "8", mods = "Command", chars = "\u00028" },
  { key = "9", mods = "Command", chars = "\u00029" },

  { key = "G", mods = "Command", chars = "\u0002[" },
  { key = "R", mods = "Command", chars = "\u0002W" },
  { key = "R", mods = "Command|Shift", chars = "\u0002S" },
  { key = "Comma", mods = "Command", chars = "\u0002(" },
  { key = "Z", mods = "Command", chars = "\u0002z" },
  { key = "F", mods = "Command", chars = "\u0002/" },
  { key = "P", mods = "Command", chars = "\u0002p" },
]
