[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[keyboard]
bindings = [
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "N", mods = "Command|Shift", action = "SpawnNewInstance" },
  { key = "F12", action = "ToggleSimpleFullscreen" },

  { key = "Space", mods = "Alt", chars = "\u0020" },
  { key = "Space", mods = "Command", chars = "\u0020" },
]
