[window]
decorations = "buttonless"
option_as_alt = "None"

[window.padding]
x = 4
y = 4

[font]
size = 17

# Nerd Font Mono == Fully monospaced, smaller icons
# Nerd Font == Partially monospaced, bigger icons (2wide icons, terminal has to support them)
#normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font" }
#normal = { family = "RecMonoLinear Nerd Font" }
#normal = { family = "RecMonoCasual Nerd Font" }
#normal = { family = "Hack Nerd Font Mono" }
#normal = { family = "BlexMono Nerd Font Mono" }

# normal = { family = "MonaspiceNe Nerd Font Mono" }
# normal = { family = "MonaspiceAr Nerd Font Mono" }
# normal = { family = "MonaspiceXe Nerd Font Mono" }
# normal = { family = "MonaspiceRn Nerd Font Mono" }
# normal = { family = "MonaspiceKr Nerd Font Mono" }

# normal = { family = "MonaspiceNe Nerd Font" }
# italic = { family = "MonaspiceAr Nerd Font" }
# bold_italic = { family = "MonaspiceAr Nerd Font" }

# LG = Large Glyphs
# L, M, S = spacing
# DZ = dotted zero
#normal = { family = "MesloLGS Nerd Font" }

[keyboard]
bindings = [
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "N", mods = "Command|Shift", action = "SpawnNewInstance" },
  { key = "B", mods = "Command", action = "ReceiveChar" },
  { key = "Space", mods = "Alt", chars = " " },
  { key = "Space", mods = "Command", chars = " " },
  { key = "F12", action = "ToggleSimpleFullscreen" },
  { key = "W", mods = "Command", chars = "\u001Bw" },
  { key = "T", mods = "Command", chars = "\u001Bt" },
  { key = "T", mods = "Command|Shift", chars = "\u001BT" },

  # Keyboard -> Shortcuts (or app shortcuts) -> Create an entry for 'Hide alacritty' (name must match) to some other shortcut
  { key = "H", mods = "Command", chars = "\u001Bh" },
  { key = "J", mods = "Command", chars = "\u001Bj" },
  { key = "K", mods = "Command", chars = "\u001Bk" },
  { key = "L", mods = "Command", chars = "\u001Bl" },

  { key = "H", mods = "Command|Shift", chars = "\u001BH" },
  { key = "J", mods = "Command|Shift", chars = "\u001BJ" },
  { key = "K", mods = "Command|Shift", chars = "\u001BK" },
  { key = "L", mods = "Command|Shift", chars = "\u001BL" },
  { key = "Return", mods = "Command|Shift", chars = "\u001B\r" },
  { key = "D", mods = "Command", chars = "\u001Bd" },
  { key = "D", mods = "Command|Shift", chars = "\u001BD" },
  { key = "S", mods = "Command", chars = "\u001Bs" },
  { key = "Key1", mods = "Command", chars = "\u001B1" },
  { key = "Key2", mods = "Command", chars = "\u001B2" },
  { key = "Key3", mods = "Command", chars = "\u001B3" },
  { key = "Key4", mods = "Command", chars = "\u001B4" },
  { key = "Key5", mods = "Command", chars = "\u001B5" },
  { key = "Key6", mods = "Command", chars = "\u001B6" },
  { key = "Key7", mods = "Command", chars = "\u001B7" },
  { key = "Key8", mods = "Command", chars = "\u001B8" },
  { key = "Key9", mods = "Command", chars = "\u001B9" },
  { key = "G", mods = "Command", chars = "\u001Bg" },
  { key = "R", mods = "Command", chars = "\u001Br" },
  { key = "R", mods = "Command|Shift", chars = "\u001BR" },
  { key = "Comma", mods = "Command", chars = "\u001B," },
  { key = "N", mods = "Command", chars = "\u001Bn" },
  { key = "Z", mods = "Command", chars = "\u001Bz" },
  { key = "F", mods = "Command", chars = "\u001Bf" },
  { key = "F", mods = "Command|Shift", chars = "\u001BF" },
  { key = "E", mods = "Command", chars = "\u001Be" },
  { key = "I", mods = "Command", chars = "\u001Bi" },
  { key = "P", mods = "Command", chars = "\u001Bp" },
]
