[shell]
args = ["bash", "--login"]
program = "/usr/bin/env"

[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[keyboard]
bindings = [
{ key = "N", mods = "Alt|Shift", action = "SpawnNewInstance" },
]
