[window]
decorations = "none"

[window.padding]
x = 4
y = 4

[shell]
args = ["bash", "-l", "-i"]
program = "/usr/bin/env"

[font]
size = 15

# Nerd Font Mono == Fully monospaced, smaller icons
# Nerd Font == Partially monospaced, bigger icons (2wide icons, terminal has to support them)
#normal = { family = "IosevkaTerm Nerd Font" }
#normal = { family = "SauceCodePro Nerd Font" }
#normal = { family = "JetBrainsMono Nerd Font" }
#normal = { family = "RecMonoCasual Nerd Font" }
normal = { family = "RecMonoLinear Nerd Font" }

#normal = { family = "IosevkaInputFixed" }
#normal = { family = "IosevkaInputFixed SmEx" }
#normal = { family = "IosevkaInputFixed Extended" }

#normal = { family = "IosevkaPragmataFixed" }
#normal = { family = "IosevkaPragmataFixed SmEx" }
#normal = { family = "IosevkaPragmataFixed Extended" }

[keyboard]
bindings = [
  { key = "N", mods = "Alt|Shift", action = "SpawnNewInstance" },

  # Disable forward and backward search
  { key = "F", mods = "Shift|Control", action = "ReceiveChar" },
  { key = "B", mods = "Shift|Control", action = "ReceiveChar" },
]
