[window]
decorations = "none"

[window.padding]
x = 4
y = 4

[shell]
args = ["bash", "-l", "-i"]
program = "/usr/bin/env"

[font]
size = 15

# Nerd Font Mono == Fully monospaced, smaller icons
# Nerd Font == Partially monospaced, bigger icons (2wide icons, terminal has to support them)
normal = { family = "IosevkaTerm Nerd Font" }
#normal = { family = "Input Mono Condensed" }

[keyboard]
bindings = [
{ key = "N", mods = "Alt|Shift", action = "SpawnNewInstance" },
]
