[window]
decorations = "none"

[terminal.shell]
args = ["bash", "-l", "-i"]
program = "/usr/bin/env"

[font]
size = 15

# Nerd Font Mono == Fully monospaced, smaller icons
# Nerd Font == Partially monospaced, bigger icons (2wide icons, terminal has to support them)
normal = { family = "Iosevka Term Nerd Font" }
#normal = { family = "SauceCodePro Nerd Font" }
#normal = { family = "JetBrainsMono Nerd Font" }
#normal = { family = "Hack Nerd Font" }
#normal = { family = "RecMonoCasual Nerd Font" }
#normal = { family = "RecMonoLinear Nerd Font" }

[keyboard]
bindings = [
  { key = "N", mods = "Alt|Shift", action = "SpawnNewInstance" },

  # Disable forward and backward search
  { key = "F", mods = "Shift|Control", action = "ReceiveChar" },
  { key = "B", mods = "Shift|Control", action = "ReceiveChar" },
]
