[window]
decorations = "none"

[window.padding]
x = 4
y = 4

[shell]
args = ["bash", "--login"]
program = "/usr/bin/env"

[font]
size = 15

[font.normal]
family = "Iosevka"

[keyboard]
bindings = [
{ key = "N", mods = "Alt|Shift", action = "SpawnNewInstance" },
]
