tap "homebrew/bundle"
tap "homebrew/services"


# Formulaes
#brew "ipython"


cask "alacritty"
cask "apache-directory-studio"
cask "bitwarden"
cask "cyberduck" # ftp client
cask "docker"
cask "firefox"
cask "flameshot"
cask "gimp"
cask "hammerspoon"
cask "iterm2"
cask "joplin"
cask "keepassxc"
cask "mpv"
cask "openwebstart"
cask "rectangle"
cask "spotify"
cask "sublime-text"
cask "syncthing"
cask "tigervnc-viewer"
cask "tunnelblick"
cask "utm"
cask "vlc"
cask "vscodium"

# vim: ft=conf
