# Taps
# -----------------------------------------------------------------------------
tap "homebrew/bundle"
tap "homebrew/services"
tap "fluxcd/tap"
tap "kcl-lang/tap"
tap "go-task/tap"

# Formulaes
# -----------------------------------------------------------------------------
# brew "fluxcd/tap/flux" # use concrete version for the cluster
brew "age"
brew "ansible"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "checkov"
brew "coreutils"
brew "cosign"
brew "cue"
brew "diffutils"
brew "dive"
brew "entr" # Run arbitrary commands when files change (I don't remember which program needs it)
brew "fd"
brew "findutils"
brew "fzf"
brew "gcc" # tree-sitter (neorg)
brew "gh"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "gnu-tar"
brew "go"
brew "go-jsonnet" # jsonnetfmt
brew "go-task"
brew "grep"
brew "helm"
brew "helm-docs"
brew "helm-ls"
brew "ipcalc"
brew "jq"
brew "jsonnet-bundler" # for tanka
brew "k9s"
brew "kcl-lang/tap/kcl"
brew "kcl-lang/tap/kcl-lsp"
brew "kind"
brew "kubecolor"
brew "kubeconform"
brew "kubernetes-cli"
brew "lazygit"
brew "luarocks"
brew "minikube"
brew "mpv"
brew "neovim"
brew "node"
brew "openssl@3"
brew "pandoc"
brew "pass"
brew "pipenv"
brew "python@3.11"
brew "rclone"
brew "riff"
brew "ripgrep"
brew "sops"
brew "sox" # sound sample translator (gp.nvim)
brew "starship"
brew "tanka"
brew "tealdeer"
brew "telnet"
brew "tenv"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "util-linux"
brew "vim"
brew "watch"
brew "websocat"
brew "wget"
brew "yq"

# Fonts
# -----------------------------------------------------------------------------
cask "font-aporetic" # iosevka from protesilaos
cask "font-ibm-plex-mono"
cask "font-iosevka"
cask "font-jetbrains-mono"
cask "font-source-code-pro"

cask "font-hack-nerd-font"
cask "font-symbols-only-nerd-font"

# Casks
# -----------------------------------------------------------------------------
cask "alacritty"
cask "cyberduck" # ftp client
cask "dbeaver-community"
cask "discord"
cask "docker"
cask "flameshot"
cask "ghostty"
cask "gimp"
cask "hammerspoon"
cask "keepassxc"
cask "microsoft-remote-desktop"
cask "obsidian"
cask "rectangle"
cask "syncthing"
cask "telegram"
cask "tigervnc-viewer"
cask "tunnelblick"
cask "utm"
cask "vlc"
cask "vscodium"
cask "zed"

# Neovim
# -----------------------------------------------------------------------------
# Formatters
brew "black"
brew "isort"
brew "prettierd"
brew "ruff"
brew "shfmt"
brew "stylua"
brew "taplo"
brew "yamlfmt"

# Linters
brew "ansible-lint"
brew "djlint"
brew "golangci-lint"
brew "proselint"
brew "shellcheck"
brew "tflint"
brew "typos-cli"
brew "yamllint"

# LSP
brew "basedpyright"
brew "bash-language-server"
brew "vscode-langservers-extracted"
brew "gopls"
brew "lua-language-server"
brew "marksman"
brew "ruff-lsp"
brew "templ"
brew "terraform-ls"
brew "typescript-language-server"
brew "yaml-language-server"

# vim: ft=conf
