k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /tmp/k9s-screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  ui:
    enableMouse: false
    headless: true
    logoless: true
    crumbsless: false
    reactive: true
    noIcons: false
  skipLatestRevCheck: true
  disablePodCounting: false
  shellPod:
    image: ghcr.io/aorith/debugpod:latest
    tty: true
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
