# ~/.zshenv
# zshenv is always sourced

export ZDOTDIR="$HOME/.config/zsh"

export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="bat -p"

source ~/githome/dotfiles/topics/shell/etc/common/exports.sh
source ~/githome/dotfiles/topics/shell/etc/common/aliases.sh

# Extended output for the time builtin.
TIMEFMT='
 time report for `%J`
   total   %*E
   user    %U
   system  %S
   cpu     %P
   mem-avg %KKB
   mem-max %MKB
'
