#!/usr/bin/env bash

echo
awk -v term_cols="${width:-$(tput cols || echo 80)}" 'BEGIN{
    s="/\\";
    for (colnum = 0; colnum<term_cols; colnum++) {
        r = 255-(colnum*255/term_cols);
        g = (colnum*510/term_cols);
        b = (colnum*255/term_cols);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum%2+1,1);
    }
    printf "\n";
}'
echo

T='gYw01'

for FG in $(seq 0 15); do
    echo -en "$(tput setaf "$FG")  $T  "
    for BG in $(seq 0 7); do
        echo -en "$(tput setab "$BG")  $T  $(tput sgr0)";
    done
    echo;
done
printf '\n'
for i in $(seq 1 255); do
    printf '%b%s%b ' "$(tput setaf "$i")" "c$i" "$(tput sgr0)"
done
printf '\n\n'
echo -n "colors: "; tput colors
echo -e 'Normal, \x1b[1mbold\x1b[22m, \x1b[3mitalic\x1b[23m, \x1b[1;3mbold italic\x1b[22;23m,' "$(tput rev)Reverse$(tput sgr0), $(tput smul)Underline$(tput sgr0)"
echo

