#!/bin/bash

T='gYw01'

for FG in $(seq 0 15); do
    echo -en "$(tput setaf "$FG")  $T  "
    for BG in $(seq 0 7); do
        echo -en "$(tput setab "$BG")  $T  $(tput sgr0)";
    done
    echo;
done
echo
echo -e 'Normal, \x1b[1mbold\x1b[22m, \x1b[3mitalic\x1b[23m, \x1b[1;3mbold italic\x1b[22;23m'

