#!/usr/bin/env bash
# vimgrep bat

# Use it with rg and fzf, for example:
# rg --line-number --color ansi . "$HOME" | fzf --ansi -d '/' -n -1 --with-nth=-1 --preview 'vgbat {} --style=full'
# the selected match has this format:
# '<path_to_file>:<line_number>:<matched_text>

command -v bat &>/dev/null && EXEC='bat' || EXEC='batcat'
file="$(cut -d':' -f1 <<< "$1")"
line="$(cut -d':' -f2 <<< "$1")"
shift
"$EXEC" "$@" --highlight-line "$line" -f "$file"
