set termguicolors
"colorscheme tempus_autumn
"colorscheme tempus_classic
"colorscheme tempus_dawn
"colorscheme tempus_day
"colorscheme tempus_dusk
"colorscheme tempus_fugit
"colorscheme tempus_future
"colorscheme tempus_night
"colorscheme tempus_past
"colorscheme tempus_rift
"colorscheme tempus_spring
"colorscheme tempus_summer
"colorscheme tempus_tempest
"colorscheme tempus_totus
"colorscheme tempus_warp
colorscheme tempus_winter
