vim.loader.enable()

require("aorith.core.colorscheme")
require("aorith.core.options")
require("aorith.core.autocmds")
require("aorith.core.keymaps")

require("aorith.plugins.lualine")
require("aorith.plugins.tree-sitter")
require("aorith.plugins.dressing")

require("aorith.plugins.fzf-lua")
require("aorith.plugins.gitsigns")
require("aorith.plugins.mini")
require("aorith.plugins.neo-tree")
require("aorith.plugins.completion")
require("aorith.plugins.lint")
require("aorith.plugins.format")
require("aorith.plugins.trouble")
require("aorith.plugins.lsp.lspconfig")
require("aorith.plugins.aerial")
