# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '$all$git_branch$git_commit$git_state$git_status${custom.container}$jobs$status$character'

[time]
disabled = false
time_format = '%H:%M:%S'
format = '[$time]($style) '
style = 'white dimmed'

[jobs]
format = '[$number jobs]($style) '
number_threshold = 1

[status]
disabled = false
format = '[$status]($style) '

[directory]
truncation_symbol = '…/'
truncation_length = 4
truncate_to_repo = false
format = "[$path]($style)[ $read_only ]($read_only_style)"

[git_status]
disabled = false

[git_metrics]
disabled = true

[git_commit]
tag_disabled = false

[python]
disabled = false
detect_extensions = []

[package]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = false

[[kubernetes.contexts]]
context_pattern = ".*/dext-eks-pro-v2$"
context_alias = "dext-eks-pro-v2"

[[kubernetes.contexts]]
context_pattern = ".*/dext-eks-pro$"
context_alias = "dext-eks-pro"

[custom.container]
description = "Active container"
when = ''' [[ -n "$CONTAINER_ID" ]] '''
command = 'echo -n "$CONTAINER_ID"'
style = "bold red"
format = '[\[$output\]]($style) '
disabled = false
