# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '${custom.container}${all}'

[character]
success_symbol = '[❯](bold blue)'

[jobs]
number_threshold = 1

[status]
disabled = false

[directory]
truncation_length = 0
format = "[$path]($style)[ $read_only ]($read_only_style)"

[git_status]
disabled = false
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_commit]
tag_disabled = false

[python]
disabled = false
format = '[(venv:$virtualenv)]($style) '
detect_extensions = []

[kubernetes]
disabled = false

[[kubernetes.contexts]]
context_pattern = ".*/dext-eks-pro-v2$"
context_alias = "dext-eks-pro-v2"

[[kubernetes.contexts]]
context_pattern = ".*/dext-eks-pro$"
context_alias = "dext-eks-pro"

[custom.container]
description = "Active container"
when = ''' [[ -n "$CONTAINER_ID" ]] '''
command = 'echo -n "$CONTAINER_ID"'
style = "bold red"
format = '[\[$output\]]($style) '
disabled = false

# Disabled
[git_metrics]
disabled = true
[package]
disabled = true
[docker_context]
disabled = true
[golang]
disabled = true
[nodejs]
disabled = true
[lua]
disabled = true
