add_newline = true

format = """
$time\
$container\
${custom.container}\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nix_shell\
$python\
$jobs\
$cmd_duration\
$status\
$line_break\
$character"""

[package]
disabled = true

[time]
disabled = false
time_format = '%H:%M'
format = '[$time]($style) '
style = 'white dimmed'

[jobs]
format = '[$number]($style) '
number_threshold = 1

[status]
disabled = false
format = '[$status]($style) '

[directory]
truncation_symbol = '…/'
truncation_length = 4
truncate_to_repo = false

[python]
detect_extensions = []

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[container]
format='[$symbol]($style) '

[custom.container]
description = "Active container"
command = 'echo $CONTAINER_ID'
when = ''' [[ -n $CONTAINER_ID ]] '''
style = "bold red"
format = '[\[$output\]]($style) '
disabled = false
