#!/bin/sh

xrdb -merge ~/.config/Xresources/Xresources
xset r rate 300 36
xset fp rehash
xsetroot -cursor_name left_ptr

#xmodmap - <<EOF
#clear lock
#keycode 66 = Home
#EOF

#autocutsel -fork &

exec i3 > /tmp/i3.log 2>&1
