#!/bin/sh

export GTK2_RC_FILES=$HOME/.config/gtk-2.0/gtkrc.conf

# Make QT automatically scale according to screen DPI
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORMTHEME=qt5ct

# Disable GTK3 apps to contact org.a11y.Bus.
export NO_AT_BRIDGE=1

export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for Java applications in wm's (dwm)

. ~/.bash_profile

#systemctl --user import-environment
#systemctl --user daemon-reload
#exec systemctl --user start --wait i3.service
