[colors]
background = '#ffffff'
foreground = '#000000'

cursor_bg = '#4a4543'
cursor_border = '#4a4543'
cursor_fg = '#f7f7f7'
selection_bg = '#4a484d'
selection_fg = '#ffffff'

ansi = [
    '#090300',
    '#990000',
    '#00993F',
    '#998D00',
    '#016A98',
    '#5E3B56',
    '#1B607E',
    '#A7A4A4',
]
brights = [
    '#5e4b4f',
    '#992030',
    '#4a5500',
    '#8a3600',
    '#2d45b0',
    '#700dc9',
    '#005289',
    '#ffffff',
]

[colors.indexed]

[metadata]
name = 'mylight'
origin_url = ''
