---
- name: Add Flatpak remotes
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    method: user
    flatpakrepo_url: "{{ item.url }}"
  loop: "{{ flatpak_remotes }}"

# name: Update flatpak remote metadata
# ansible.builtin.command: flatpak update --appstream

- name: Install Flatpak packages (FlatHub)
  community.general.flatpak:
    name: "{{ flathub_common_packages }}"
    state: present
    method: user
    remote: "flathub"

- name: Install Flatpak packages (FlatHub) (non NixOS)
  community.general.flatpak:
    name: "{{ flathub_non_nixos_packages }}"
    state: present
    method: user
    remote: "flathub"
  when: ansible_os_family != "NixOS" and flatpak_non_nixos_packages is defined and flatpak_non_nixos_packages | length > 0
