[colors.bright]
black = "#5C5F75"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#BCC0CC"
yellow = "#DF8E1D"

[colors.dim]
black = "#4C4F67"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[colors.normal]
black = "#4C4F67"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[colors.primary]
background = "#f9f9e7"
bright_foreground = "#3C3F59"
dim_foreground = "#2C2F49"
foreground = "#000000"
